#!/usr/bin/env bash
# ============================== ==============================
# Bootstrap Terraform State Backend (GCS)
# ============================== ==============================
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
export PLATFORM_DIR="${PROJECT_ROOT}/platform_tooling"

# ============================== ==============================
# Configuration & Expected Variables
# ============================== ==============================
ENV_FILE="${PLATFORM_DIR}/config/platform.env"

REQUIRED_VARS=(
    "REPO_NAME"
    "GCP_PROJECT_ID"
    "GCP_REGION"
    "STATE_BUCKET_PREFIX"
)

OPTIONAL_VARS=(
    "BACKEND_BUCKET_NAME"
)

# ============================== ==============================
# Initialization
# ============================== ==============================
source "${PLATFORM_DIR}/scripts/lib.sh"

# Load required vars (fails fast if missing)
load_env_vars "$ENV_FILE" "${REQUIRED_VARS[@]}"

# Load optional vars (silently ignores if missing or commented out)
for var in "${OPTIONAL_VARS[@]}"; do
    value=$(grep -E "^${var}=" "$ENV_FILE" 2>/dev/null | head -n 1 | cut -d'=' -f2- | sed -e 's/^["'\'']//' -e 's/["'\'']$//' || true)
    if [[ -n "$value" ]]; then
        declare -g "$var=$value"
    fi
done

# ============================== ==============================
# Functions
# ============================== ==============================

check_dependencies() {
    require_command "gcloud"
}

verify_auth() {
    require_gcloud_auth
}

compute_bucket_name() {
    # Use provided BACKEND_BUCKET_NAME, or fall back to computed project-wide default
    if [[ -n "${BACKEND_BUCKET_NAME:-}" ]]; then
        echo "${BACKEND_BUCKET_NAME}"
    else
        echo "${STATE_BUCKET_PREFIX}-${GCP_PROJECT_ID}"
    fi
}

ensure_bucket() {
    local bucket_name="$1"
    local project_id="$2"
    local region="$3"

    log "INFO" "Target Shared State Bucket: gs://${bucket_name}"

    if gcloud storage buckets describe "gs://${bucket_name}" --project="${project_id}" >/dev/null 2>&1; then
        log "SUCCESS" "State bucket already exists."
    else
        log "INFO" "State bucket not found. Creating gs://${bucket_name} in ${region}..."

        gcloud storage buckets create "gs://${bucket_name}" \
            --project="${project_id}" \
            --location="${region}" \
            --uniform-bucket-level-access

        gcloud storage buckets update "gs://${bucket_name}" --versioning

        log "SUCCESS" "State bucket created and configured."
    fi
}

generate_backend_config() {
    local bucket_name="$1"
    local env="$2"
    local repo_name="$3"
    local config_file="$4"

    # The prefix isolates this specific repo and environment within the shared bucket
    # e.g., "env/landing-zone/dev"
    local prefix="env/${repo_name}/${env}"

    log "INFO" "Writing backend config to ${config_file}..."
    cat <<EOF > "$config_file"
# ============================== ==============================
# Auto-generated by bootstrap-state.sh
# ============================== ==============================
bucket = "${bucket_name}"
prefix = "${prefix}"
EOF
    log "SUCCESS" "Backend configuration generated."
}

# ============================== ==============================
# Main Execution
# ============================== ==============================

if [[ $# -eq 0 ]]; then
    log "ERROR" "Usage: $0 <environment>"
    exit 1
fi
ENV="$1"

# CRITICAL FIX: Skip GCS bootstrap entirely for local development
if [[ "$ENV" == "local" ]]; then
    log "INFO" "Environment is 'local'. Skipping GCS state bootstrap. Using local backend."
    exit 0
fi

BUCKET_NAME=$(compute_bucket_name)
BACKEND_CONFIG_FILE="${PLATFORM_DIR}/config/backend-${ENV}.hcl"

check_dependencies
verify_auth
ensure_bucket "$BUCKET_NAME" "$GCP_PROJECT_ID" "$GCP_REGION"
generate_backend_config "$BUCKET_NAME" "$ENV" "$REPO_NAME" "$BACKEND_CONFIG_FILE"

log "SUCCESS" "Platform bootstrapping complete for repo: ${REPO_NAME}."
