#!/usr/bin/env bash
# ============================== ============================== ==============================
# Bootstrap Terraform State Backend (GCS)
# ============================== ============================== ==============================
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
export PLATFORM_DIR="${PROJECT_ROOT}/platform_tooling"

# ============================== ==============================
# Configuration & Expected Variables
# ============================== ==============================
ENV_FILE="${PLATFORM_DIR}/config/platform.env"

# Explicitly list all variables this script requires from the env file
EXPECTED_VARS=(
    "GCP_PROJECT_ID"
    "GCP_REGION"
    "STATE_BUCKET_PREFIX"
)

# ============================== ==============================
# Initialization
# ============================== ==============================
source "${PLATFORM_DIR}/scripts/lib.sh"
load_env_vars "$ENV_FILE" "${EXPECTED_VARS[@]}"

# ============================== ==============================
# Arguments
# ============================== ==============================
if [[ $# -eq 0 ]]; then
    log "ERROR" "Usage: $0 <environment>"
    exit 1
fi
ENV="$1"

# ============================== ==============================
# Main Logic
# ============================== ==============================
BUCKET_NAME="${STATE_BUCKET_PREFIX}-${GCP_PROJECT_ID}-${ENV}"
BACKEND_CONFIG_FILE="${PLATFORM_DIR}/config/backend-${ENV}.hcl"

require_command "gcloud"
require_gcloud_auth

log "INFO" "Target State Bucket: gs://${BUCKET_NAME}"

# Check if bucket exists using modern gcloud storage API
if gcloud storage buckets describe "gs://${BUCKET_NAME}" --project="${GCP_PROJECT_ID}" >/dev/null 2>&1; then
    log "SUCCESS" "State bucket already exists."
else
    log "INFO" "State bucket not found. Creating gs://${BUCKET_NAME} in ${GCP_REGION}..."

    gcloud storage buckets create "gs://${BUCKET_NAME}" \
        --project="${GCP_PROJECT_ID}" \
        --location="${GCP_REGION}" \
        --uniform-bucket-level-access

    gcloud storage buckets update "gs://${BUCKET_NAME}" --versioning

    log "SUCCESS" "State bucket created and configured."
fi

# Generate backend config dynamically
log "INFO" "Writing backend config to ${BACKEND_CONFIG_FILE}..."
cat <<EOF > "$BACKEND_CONFIG_FILE"

# ============================== ==============================
# Auto-generated by bootstrap-state.sh
# ============================== ==============================

bucket = "${BUCKET_NAME}"
prefix = "env/${ENV}"
EOF

log "SUCCESS" "Backend configuration generated."
